config/routes.rb
Rails.application.routes.draw do
  root 'sheeps#index', as: 'home'

  get 'sheeps/index'
  get 'sheeps/show'

  resources :sheeps

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adult.rb
class Adult < ApplicationRecord

  belongs_to :sheep

end
class Adult < ApplicationRecord

	belongs_to :father, class_name: 'Sheep', optional: true
  	belongs_to :mother, class_name: 'Sheep', optional: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/moment.rb
class Moment < ApplicationRecord

  belongs_to :sheep
  
end

app/models/race.rb
class Race < ApplicationRecord

  belongs_to :sheep
  
end

app/models/reason.rb
class Reason < ApplicationRecord

  belongs_to :sheep

end

app/models/sheep.rb
class Sheep < ApplicationRecord
  validates :levensnummer, length: { minimum: 2 }

  has_many :races
  has_many :moments
  has_many :adults
  has_many :reasons

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sheeps_controller.rb
class SheepsController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sheeps_helper.rb
module SheepsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Schapendb</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #71da71;">
  <%= link_to "Oer van Ovis", home_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to "Schapen", sheeps_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Rassen", sheeps_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/sheeps/index.html.erb
<h1>Sheeps#index</h1>
<p>Find me in app/views/sheeps/index.html.erb</p>

app/views/sheeps/show.html.erb
<h1>Sheeps#show</h1>
<p>Find me in app/views/sheeps/show.html.erb</p>